### ISSUE TITLE
Cannot use VSCode extension because Plank pod doesn't start up

### ISSUE THREAD

**Issue by christian-posta** [solo-io/squash#134]
or cannot be started for some reason. I'm getting this:

`
serviceaccounts "squash-plank" not found Error: serviceaccounts "squash-plank" not found Usage: squashctl [flags] squashctl [command] Available Commands: completion generate auto completion for your shell deploy deploy squash or a demo microservice help Help about any command squash manage the squash utils call various squash utils Flags: --container string Container to debug --container-repo string debug container repo to use (default "quay.io/solo-io") --container-version string debug container version to use (default "0.5.1") --crisock string The path to the CRI socket (default "/var/run/dockershim.sock") --debugger string Debugger to use -h, --help help for squashctl --json output json format --localport int local port to use to connect to debugger (defaults to random free port) --machine ...
`

**Comment by sanha** [comment]
It seem's that this issue is resolved via # #146.
I checked that the demo case works well in my mac OS.
![image](https://user-images.githubusercontent.com/8844176/54583667-39def000-4a58-11e9-9388-f0d1ce0ee69c.png)
Env: Mac Mojave, kubectl v1.13.4, minikube v0.35.0, squashctl v0.5.5, vscode extension v0.5.5, vscode v1.32.1

@mitchdraft could you close this issue? Thanks!

**Comment by mitchdraft** [comment]
glad this is working for you @sanha , yes, there was an issue with the download path for squash v0.5.4
thanks for flagging this issue, closing
