### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by maminio** [solo-io/squash#197]
From your BUILDFILE.md, when I run :
```go get github.com/solo-io/squash```
I get `can't load package: package github.com/solo-io/squash: no Go files in /Users/******/golang/src/github.com/solo-io/squash`

**Comment by mitchdraft** [comment]
Hi @maminio, thanks for pointing out the issue. 
I think you're referring to:

```bash
    # Download the source by using go get
    go get github.com/solo-io/squash

    # or by using git clone
    # mkdir -p $GOPATH/src/github.com/solo-io
    # cd $GOPATH/src/github.com/solo-io
    # git clone https://github.com/solo-io/squash.git

    cd $GOPATH/src/github.com/solo-io/squash
    git checkout -b master
```

go get must not be working since we moved all the go scripts out of the root directory

I think the `git clone` workflow should work

I use a subset of the steps our CI uses, as defined in `cloudbuild.yaml`, the `BUILDFILE.md` is intended as a "getting started" guide.

If you have a chance to try it out, please feel free to submit a PR with your workflow.

Otherwise I will update this soon

**Comment by mitchdraft** [comment]
docs have been updated
https://github.com/solo-io/squash/blob/master/BUILDING.md
